from .FSNETCMD_LOGON import FSNETCMD_LOGON
from .FSNETCMD_LOGOFF import FSNETCMD_LOGOFF
from .FSNETCMD_ERROR import FSNETCMD_ERROR
from .FSNETCMD_LOADFIELD import FSNETCMD_LOADFIELD
from .FSNETCMD_ADDOBJECT import FSNETCMD_ADDOBJECT
from .FSNETCMD_READBACK import FSNETCMD_READBACK
from .FSNETCMD_SMOKECOLOR import FSNETCMD_SMOKECOLOR
from .FSNETCMD_JOINREQUEST import FSNETCMD_JOINREQUEST
from .FSNETCMD_JOINAPPROVAL import FSNETCMD_JOINAPPROVAL
from .FSNETCMD_REJECTJOINREQ import FSNETCMD_REJECTJOINREQ
from .FSNETCMD_AIRPLANESTATE import FSNETCMD_AIRPLANESTATE
from .FSNETCMD_UNJOIN import FSNETCMD_UNJOIN
from .FSNETCMD_REMOVEAIRPLANE import FSNETCMD_REMOVEAIRPLANE
from .FSNETCMD_REQUESTTESTAIRPLANE import FSNETCMD_REQUESTTESTAIRPLANE
from .FSNETCMD_KILLSERVER import FSNETCMD_KILLSERVER
from .FSNETCMD_PREPARESIMULATION import FSNETCMD_PREPARESIMULATION
from .FSNETCMD_TESTPACKET import FSNETCMD_TESTPACKET
from .FSNETCMD_LOCKON import FSNETCMD_LOCKON
from .FSNETCMD_REMOVEGROUND import FSNETCMD_REMOVEGROUND
from .FSNETCMD_MISSILELAUNCH import FSNETCMD_MISSILELAUNCH
#from .FSNETCMD_GROUNDSTATE import FSNETCMD_GROUNDSTATE
from .FSNETCMD_GETDAMAGE import FSNETCMD_GETDAMAGE
#from .FSNETCMD_GNDTURRETSTATE import FSNETCMD_GNDTURRETSTATE
#from .FSNETCMD_SETTESTAUTOPILOT import FSNETCMD_SETTESTAUTOPILOT
#from .FSNETCMD_REQTOBESIDEWINDOWOFSVR import FSNETCMD_REQTOBESIDEWINDOWOFSVR
#from .FSNETCMD_ASSIGNSIDEWINDOW import FSNETCMD_ASSIGNSIDEWINDOW
#from .FSNETCMD_RESENDAIRREQUEST import FSNETCMD_RESENDAIRREQUEST
#from .FSNETCMD_RESENDGNDREQUEST import FSNETCMD_RESENDGNDREQUEST
#from .FSNETCMD_VERSIONNOTIFY import FSNETCMD_VERSIONNOTIFY
from .FSNETCMD_AIRCMD import FSNETCMD_AIRCMD
#from .FSNETCMD_USEMISSILE import FSNETCMD_USEMISSILE
from .FSNETCMD_TEXTMESSAGE import FSNETCMD_TEXTMESSAGE
from .FSNETCMD_ENVIRONMENT import FSNETCMD_ENVIRONMENT
#from .FSNETCMD_NEEDRESENDJOINAPPROVAL import FSNETCMD_NEEDRESENDJOINAPPROVAL
#from .FSNETCMD_REVIVEGROUND import FSNETCMD_REVIVEGROUND
from .FSNETCMD_WEAPONCONFIG import FSNETCMD_WEAPONCONFIG
#from .FSNETCMD_LISTUSER import FSNETCMD_LISTUSER
#from .FSNETCMD_QUERYAIRSTATE import FSNETCMD_QUERYAIRSTATE
#from .FSNETCMD_USEUNGUIDEDWEAPON import FSNETCMD_USEUNGUIDEDWEAPON
#from .FSNETCMD_AIRTURRETSTATE import FSNETCMD_AIRTURRETSTATE
#from .FSNETCMD_CTRLSHOWUSERNAME import FSNETCMD_CTRLSHOWUSERNAME
#from .FSNETCMD_CONFIRMEXISTENCE import FSNETCMD_CONFIRMEXISTENCE
#from .FSNETCMD_CONFIGSTRING import FSNETCMD_CONFIGSTRING
#from .FSNETCMD_LIST import FSNETCMD_LIST
#from .FSNETCMD_GNDCMD import FSNETCMD_GNDCMD
#from .FSNETCMD_REPORTSCORE import FSNETCMD_REPORTSCORE
#from .FSNETCMD_SERVER_FORCE_JOIN import FSNETCMD_SERVER_FORCE_JOIN
#from .FSNETCMD_FOGCOLOR import FSNETCMD_FOGCOLOR
#from .FSNETCMD_SKYCOLOR import FSNETCMD_SKYCOLOR
#from .FSNETCMD_GNDCOLOR import FSNETCMD_GNDCOLOR
#from .FSNETCMD_RESERVED_FOR_LIGHTCOLOR import FSNETCMD_RESERVED_FOR_LIGHTCOLOR
#from .FSNETCMD_GENERATEATTACKER import FSNETCMD_GENERATEATTACKER


__all__ = ["FSNETCMD_LOGON", "FSNETCMD_LOGOFF", "FSNETCMD_ERROR",
           "FSNETCMD_LOADFIELD", "FSNETCMD_ADDOBJECT",
           "FSNETCMD_READBACK", "FSNETCMD_SMOKECOLOR",
           "FSNETCMD_JOINREQUEST", "FSNETCMD_JOINAPPROVAL",
           "FSNETCMD_REJECTJOINREQ", "FSNETCMD_AIRPLANESTATE",
           "FSNETCMD_UNJOIN", "FSNETCMD_REMOVEAIRPLANE",
           "FSNETCMD_REQUESTTESTAIRPLANE", "FSNETCMD_KILLSERVER",
           "FSNETCMD_PREPARESIMULATION", "FSNETCMD_TESTPACKET",
           "FSNETCMD_LOCKON", "FSNETCMD_REMOVEGROUND",
           "FSNETCMD_MISSILELAUNCH", "FSNETCMD_GETDAMAGE",
           "FSNETCMD_WEAPONCONFIG", "FSNETCMD_AIRCMD",
           "FSNETCMD_TEXTMESSAGE", "FSNETCMD_ENVIRONMENT"]
